name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: webapp
        run: make install

      - name: Run unit tests
        working-directory: webapp
        run: make test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-webapp:latest -f webapp/Dockerfile . 
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-webapp:latest

      - name: Deploy to staging (local container)
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/ci-webapp:latest

      - name: Wait for container to start
        run: sleep 5

      - name: Run integration tests against deployed application
        run: |
          if ! curl -s -f http://localhost:8080 | grep "Hello, Continuous Integration!"; then
            echo "Integration tests against deployed application failed!"
            exit 1
          fi

      - name: Simulate production deployment (conditional)
        if: success()
        run: echo "Deployed to production!"
