name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated version

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated version
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r part-2_tasks/task4-ci-pipeline/webapp/requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Updated version

      - name: Login to DockerHub
        uses: docker/login-action@v2 # Updated version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-webapp:latest part-2_tasks/task4-ci-pipeline/webapp/
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-webapp:latest

      - name: Deploy to Docker Hub
        run: echo "Deployed to Docker Hub"
